export type App = {
  slug: string;
  name: string;
  chinese: string;
  category: string;
  westernEquiv: string;
  desc: string;
  why: string;
  tips: string[];
  setupSteps?: { title: string; detail: string }[];
  warningNote?: string;
  color: string;
  emoji: string;
};

export const APPS: App[] = [
  {
    slug: "wechat",
    name: "WeChat",
    chinese: "微信",
    category: "Communication & Payments",
    westernEquiv: "WhatsApp + Apple Pay",
    desc: "China's super-app. Messaging, payments, mini-programs, ride-hailing — everything runs through WeChat.",
    why: "Mandatory. Hotels, restaurants, tickets, QR code payments — you'll need this daily.",
    tips: [
      "Download before arriving — registration requires a phone number and may need a friend to verify",
      "Add WeChat Pay by linking an international Visa/Mastercard (2023+)",
      "Use 'Scan' to pay at shops and scan menus",
      "Mini Programs (小程序) replace many standalone apps — search inside WeChat",
    ],
    setupSteps: [
      { title: "Download WeChat", detail: "Available on App Store and Google Play globally. Download before your trip." },
      { title: "Register with your phone number", detail: "Use your home country number (+1, +44, etc.). You'll get an SMS code." },
      { title: "Get verified by a friend", detail: "New accounts need an existing WeChat user with 100+ friends to scan your QR and verify you. Ask a friend who uses WeChat." },
      { title: "Set up WeChat Pay", detail: "Tap Me → Wallet → Cards → Add Card. Choose international card (Visa/MC/JCB)." },
      { title: "Complete real-name verification", detail: "Upload a photo of your passport. Required for payment. Takes 1–3 business days." },
      { title: "Set a payment PIN", detail: "Choose a 6-digit PIN. This is used for every payment transaction." },
      { title: "Test with a small scan", detail: "Find any WeChat Pay QR code (convenience stores work great) and test a ¥1 purchase." },
    ],
    warningNote: "Account creation can be tricky — WeChat sometimes blocks new registrations from new devices. Set up at least 2 weeks before your trip in case there are issues.",
    color: "text-green-400",
    emoji: "💬",
  },
  {
    slug: "alipay",
    name: "Alipay",
    chinese: "支付宝",
    category: "Payments",
    westernEquiv: "PayPal / Apple Pay",
    desc: "The other major mobile payment platform. Backed by Alibaba. Required for many online and in-store purchases.",
    why: "Some vendors only take Alipay. Also great for international tourist features like real-name verification.",
    tips: [
      "Foreigners can now link Visa/Mastercard/American Express directly",
      "Enable 'International Card' mode in settings",
      "Use the 'Tour Pass' feature specifically designed for foreign tourists",
      "Keep a few hundred yuan limit — international cards have daily caps",
    ],
    setupSteps: [
      { title: "Download Alipay", detail: "Available on App Store / Google Play globally. Use the same app as locals — no separate international version needed." },
      { title: "Register with your phone number", detail: "Use your home country number. SMS verification code will be sent." },
      { title: "Tap 'International Card' in Settings", detail: "Go to: Me → Bank Cards → Add Card → International Card. This flow is designed specifically for foreigners." },
      { title: "Add your card details", detail: "Visa, Mastercard, American Express, and JCB are accepted. Enter card number, expiry, and CVV." },
      { title: "Upload passport for identity verification", detail: "Photo of passport data page. Processing takes 1–3 business days — do this before your trip!" },
      { title: "Check spending limit", detail: "International cards have a CNY 6,500/day limit (~$900 USD). Sufficient for most travelers." },
      { title: "Test a small payment", detail: "Scan any Alipay QR code. A convenience store is a safe first test." },
    ],
    warningNote: "Do this at least a week before your trip — the identity verification step can take 1–3 business days and sometimes requires re-submission.",
    color: "text-blue-400",
    emoji: "💳",
  },
  {
    slug: "xiaohongshu",
    name: "Xiaohongshu",
    chinese: "小红书",
    category: "Travel & Discovery",
    westernEquiv: "Instagram + Yelp",
    desc: "The go-to app for authentic travel tips, restaurant finds, and hidden gems. Think Pinterest meets TripAdvisor, entirely in Chinese.",
    why: "Locals use this to discover the best spots. Even without reading Chinese, the photos tell a story.",
    tips: [
      "Search your city name in Chinese (e.g. 上海 for Shanghai) for top posts",
      "Use Google Translate camera to read Chinese posts",
      "Look for posts tagged 外国人 (foreigner) for tourist-friendly tips",
      "Save posts to a collection before you go — no VPN needed for the app inside China",
    ],
    setupSteps: [
      { title: "Download Xiaohongshu (Little Red Book)", detail: "Available on App Store as 'Xiaohongshu' or 'RedNote'. Also on Google Play." },
      { title: "Register with phone number or email", detail: "International phone numbers and emails work. No VPN needed for setup." },
      { title: "Search by city in Chinese", detail: "Type '上海' (Shanghai), '北京' (Beijing), '成都' (Chengdu), etc. into the search bar for local content." },
      { title: "Use Google Translate camera", detail: "Point your phone camera at posts with Google Translate open to read Chinese captions in real-time." },
      { title: "Save posts to collections", detail: "Tap the bookmark icon on any post to save it. Create collections like 'Restaurants' and 'Sights' before your trip." },
    ],
    color: "text-red-400",
    emoji: "📕",
  },
  {
    slug: "didi",
    name: "DiDi",
    chinese: "滴滴",
    category: "Transport",
    westernEquiv: "Uber",
    desc: "China's dominant ride-hailing app. More reliable than taxis in most cities, and drivers are rated.",
    why: "Taxis are hard to hail and drivers rarely speak English. DiDi has an English mode and shows the route.",
    tips: [
      "Download the international version from App Store/Google Play",
      "Enable English mode in settings",
      "Pay via WeChat Pay or Alipay linked to your account",
      "Cheaper than taxis for airport transfers",
      "Show the driver your destination in Chinese characters",
    ],
    setupSteps: [
      { title: "Download DiDi International", detail: "Search 'DiDi' on App Store or Google Play. The international version supports English." },
      { title: "Register with your phone number", detail: "International numbers work. SMS verification code will be sent." },
      { title: "Switch to English", detail: "Go to Settings → Language → English. The app interface will switch immediately." },
      { title: "Add a payment method", detail: "Link your WeChat Pay or Alipay account, or add an international card directly." },
      { title: "Enter your destination", detail: "Type in English — DiDi understands English destination names for major landmarks." },
      { title: "Show driver your destination", detail: "Once matched, show the driver the in-app destination pin. No Chinese needed." },
    ],
    color: "text-orange-400",
    emoji: "🚗",
  },
  {
    slug: "amap",
    name: "Amap (高德地图)",
    chinese: "高德地图",
    category: "Navigation",
    westernEquiv: "Google Maps",
    desc: "The most accurate map app inside China. Google Maps has poor data for China — use this instead.",
    why: "Real-time transit, metro routes, walking directions, live traffic. Works offline too.",
    tips: [
      "Switch to English mode in settings (partial English UI)",
      "Works without a VPN inside China",
      "Better transit data than Apple Maps for Chinese cities",
      "Use voice navigation — set to English or Mandarin",
      "Available on App Store internationally",
    ],
    setupSteps: [
      { title: "Download Amap (高德地图)", detail: "Available on App Store internationally. Search 'Amap' or '高德地图'." },
      { title: "Allow location access", detail: "Grant location permission for accurate navigation and nearby search." },
      { title: "Switch to English (partial)", detail: "Go to Me → Settings → Language. Note: the map labels will stay in Chinese but the UI switches." },
      { title: "Search a destination", detail: "Type in English — major landmarks, metro stations, and tourist sites are all indexed in English." },
      { title: "Use transit mode", detail: "Tap the 'Transit' tab for metro, bus, and combined routes. Extremely accurate for all Chinese cities." },
      { title: "Download offline maps", detail: "Tap Offline Maps → your city to download for use when you have no signal." },
    ],
    color: "text-yellow-400",
    emoji: "🗺️",
  },
  {
    slug: "dianping",
    name: "Dianping",
    chinese: "大众点评",
    category: "Food & Reviews",
    westernEquiv: "Yelp",
    desc: "China's Yelp. Millions of restaurant reviews, ratings, photos and menus.",
    why: "Find the best local restaurants near you with real reviews. More reliable than TripAdvisor for China.",
    tips: [
      "Filter by 外卖 (delivery) or 堂食 (dine-in)",
      "Look for the red star rating — 4.5+ is excellent",
      "Photos are your best friend — browse before deciding",
      "Use Google Translate on the menu screenshots in reviews",
    ],
    setupSteps: [
      { title: "Download Dianping", detail: "App Store / Google Play — search '大众点评'. Register with phone number." },
      { title: "Allow location access", detail: "Required to show restaurants near you. The app will show your area automatically." },
      { title: "Browse by category", detail: "Icons at the top cover: 美食 (food), 休闲 (leisure), 酒店 (hotels), 景点 (sights). Tap any category." },
      { title: "Use photos to choose", detail: "Every listing has photos uploaded by customers. Browse photos to understand the vibe before going." },
      { title: "Check reviews with Translate", detail: "Screenshot review text and use Google Translate or Baidu Translate camera to read them." },
      { title: "Save favorites", detail: "Tap the ❤️ icon on any listing to save it to your collection. Build a list before going out." },
    ],
    color: "text-pink-400",
    emoji: "🍜",
  },
  {
    slug: "meituan",
    name: "Meituan",
    chinese: "美团",
    category: "Food Delivery & More",
    westernEquiv: "DoorDash + Grubhub",
    desc: "Food delivery giant. Also does hotel bookings, bike rentals, and attraction tickets.",
    why: "Order food to your hotel room, rent bikes, book tickets — all in one.",
    tips: [
      "Requires a Chinese phone number for full access (use hotel staff to help)",
      "Meituan bikes (美团单车) are everywhere — scan QR code to unlock",
      "Use for purchasing tickets to popular attractions in advance",
    ],
    color: "text-yellow-300",
    emoji: "🛵",
  },
  {
    slug: "ctrip",
    name: "Ctrip (Trip.com)",
    chinese: "携程",
    category: "Travel Booking",
    westernEquiv: "Expedia / Booking.com",
    desc: "China's largest travel booking platform. Flights, hotels, high-speed rail, tours.",
    why: "Book domestic flights and 高铁 (high-speed rail) tickets here. Often cheaper than international sites.",
    tips: [
      "Available in English at Trip.com",
      "Book 高铁 tickets here — you'll need your passport number",
      "Collect and show your tickets at the station with your passport",
      "Hotel prices are often lower than Booking.com for Chinese properties",
    ],
    setupSteps: [
      { title: "Use Trip.com (not the Chinese app)", detail: "Go to trip.com — this is the international version of Ctrip. Fully in English." },
      { title: "Create an account", detail: "Register with your email. Your international credit card will work for payment." },
      { title: "Book high-speed rail", detail: "Search Trains → select your route → choose a seat class. G-class (高铁) is fastest." },
      { title: "Enter your passport details", detail: "Chinese rail requires your passport number for each traveler. Enter exactly as it appears." },
      { title: "Receive your e-ticket", detail: "You'll get a booking confirmation. At the station, show your e-ticket and passport to collect a paper ticket or use the QR code." },
      { title: "Book domestic flights", detail: "Often cheaper than international booking sites. Select 'Flights' and compare with your usual site." },
    ],
    color: "text-blue-300",
    emoji: "✈️",
  },
  {
    slug: "baidu-translate",
    name: "Baidu Translate",
    chinese: "百度翻译",
    category: "Utilities",
    westernEquiv: "Google Translate",
    desc: "Best translation app to use inside China — doesn't require a VPN and works offline.",
    why: "Translate menus, signs, conversations in real-time. Camera translation is excellent for Chinese characters.",
    tips: [
      "Download Chinese language pack for offline use",
      "Camera mode (拍照翻译) is excellent for menus",
      "Conversation mode lets you have real-time bilingual conversations",
      "Works without VPN — unlike Google Translate",
    ],
    setupSteps: [
      { title: "Download Baidu Translate", detail: "App Store / Google Play. Works inside China without a VPN — essential." },
      { title: "Download offline Chinese pack", detail: "Settings → Offline Translation → Chinese (Simplified). Required for use without internet." },
      { title: "Use camera translation", detail: "Tap the camera icon → point at any text → real-time overlay translation appears. Perfect for menus." },
      { title: "Use conversation mode", detail: "Tap the microphone icon → speak in English → Baidu translates to Chinese for the other person to hear, and vice versa." },
      { title: "Set up handwriting input", detail: "Tap the keyboard icon → select handwriting → draw Chinese characters you want to look up." },
    ],
    color: "text-blue-500",
    emoji: "🌐",
  },
  {
    slug: "alipay-health-code",
    name: "Alipay Health Code",
    chinese: "健康码 / 随申码",
    category: "Utilities",
    westernEquiv: "N/A",
    desc: "QR-code based ID system used at transit hubs, venues, and hotels in some cities.",
    why: "Some venues and high-speed rail stations still scan these. Worth setting up proactively.",
    tips: [
      "Set up within Alipay using your passport",
      "Not always required but useful to have",
      "Hotel check-in may ask for it in some cities",
    ],
    color: "text-green-300",
    emoji: "🟢",
  },
  {
    slug: "12306",
    name: "12306",
    chinese: "铁路12306",
    category: "Transport",
    westernEquiv: "Trainline / Amtrak",
    desc: "China's official high-speed rail (高铁) ticketing app. The only official source for domestic train tickets.",
    why: "High-speed rail is the best way to travel between cities. 12306 gives you direct booking without third-party fees.",
    tips: [
      "Register with your passport number — you'll use it for ID verification at stations",
      "English version available under Settings → Language",
      "Book early for popular routes (Beijing–Shanghai, Beijing–Xi'an)",
      "G-trains are fastest (高铁), D-trains are slightly slower but still excellent",
      "Collect paper ticket at station or use the e-ticket QR code on the app",
    ],
    setupSteps: [
      { title: "Download 12306", detail: "App Store / Google Play. The app has an English option — look for the globe icon on the login screen." },
      { title: "Register with your passport", detail: "Select 'Foreign Passport' during registration. Enter your passport number exactly as shown." },
      { title: "Switch to English", detail: "Settings (设置) → Language (语言) → English." },
      { title: "Search your route", detail: "Select departure and arrival city, date, and passenger count. Available seats show by class." },
      { title: "Choose your seat class", detail: "Business Seat (商务座) → First Class (一等座) → Second Class (二等座). Second class is excellent value." },
      { title: "Pay with international card", detail: "UnionPay, Visa, or Mastercard accepted. You may need to add a card in the Wallet section first." },
      { title: "Collect or use e-ticket", detail: "At the station, scan your passport at the automated gate OR show your e-ticket QR code. No paper ticket needed." },
    ],
    color: "text-red-300",
    emoji: "🚄",
  },
  {
    slug: "taobao",
    name: "Taobao",
    chinese: "淘宝",
    category: "Shopping",
    westernEquiv: "Amazon / eBay",
    desc: "China's largest online marketplace with hundreds of millions of products. Everything from electronics to street food delivery.",
    why: "Extremely cheap prices. Great for buying local SIM top-ups, travel accessories, and city-specific gifts.",
    tips: [
      "Use Google Translate camera to read product listings",
      "Seller ratings matter — look for 皇冠 (crown) sellers",
      "Pay via Alipay (same ecosystem — it integrates seamlessly)",
      "Standard shipping inside China is 1–3 days and usually free",
      "Search by image: tap the camera icon to find similar items",
    ],
    setupSteps: [
      { title: "Download Taobao", detail: "App Store / Google Play. Register with your phone number and link your Alipay account." },
      { title: "Link Alipay for payment", detail: "Taobao and Alipay are both Alibaba — they link automatically when you sign in with the same account." },
      { title: "Search in Chinese for better results", detail: "Use Google Translate to look up what you want in Chinese, then paste it into Taobao's search bar." },
      { title: "Check seller ratings", detail: "Look for 皇冠 (crown) icons next to seller names — these indicate high-volume, high-rated sellers." },
      { title: "Read product details with Translate", detail: "Screenshot product pages and use Baidu Translate camera to understand specs and descriptions." },
      { title: "Enter your hotel as delivery address", detail: "Chinese addresses should be entered in Chinese — ask hotel staff to write the address for you." },
    ],
    color: "text-orange-300",
    emoji: "🛒",
  },
  {
    slug: "hellobike",
    name: "Hellobike",
    chinese: "哈啰出行",
    category: "Transport",
    westernEquiv: "Lime / Bird (dockless bikes)",
    desc: "China's largest shared bike platform. Scan a QR code, unlock a bike, ride anywhere, park anywhere.",
    why: "The cheapest and most convenient last-mile transport. Perfect for exploring parks, hutongs, and areas with no metro.",
    tips: [
      "Requires Alipay login — Alipay users get free unlocks bundled in some cities",
      "Bikes cost ¥1.5–2 per 30 minutes",
      "Meituan bikes (美团单车) and DiDi bikes work the same way if Hellobike isn't available",
      "Park within the designated zones (white painted areas on the ground)",
      "Available in almost every Chinese city including smaller tier-3 cities",
    ],
    setupSteps: [
      { title: "Download Hellobike (哈啰出行)", detail: "App Store / Google Play. Sign in with your Alipay account for the smoothest experience." },
      { title: "Link Alipay", detail: "Alipay users in some cities get free 30-minute rides bundled in their membership. Check the Hellobike promotions tab." },
      { title: "Find a bike on the map", detail: "Open the app and blue dots show nearby bikes. Walk to one and scan its QR code." },
      { title: "Scan the QR code to unlock", detail: "Point your camera at the QR code on the bike's handlebar lock. It unlocks immediately." },
      { title: "Ride and park in designated zones", detail: "White rectangles painted on the ground are official parking zones. Park only within these to avoid fines." },
      { title: "End the ride in the app", detail: "Tap 'End Ride' in the app once you've parked. The lock will click shut automatically. Payment is charged to Alipay." },
    ],
    color: "text-teal-400",
    emoji: "🚲",
  },
  {
    slug: "pleco",
    name: "Pleco",
    chinese: "Pleco",
    category: "Utilities",
    westernEquiv: "Google Translate (for Chinese)",
    desc: "The gold standard Chinese dictionary app for foreigners. Character lookup, handwriting input, flashcards, and offline dictionaries.",
    why: "When Baidu Translate fails you, Pleco delivers. Essential for learning characters, reading signs, and understanding menus offline.",
    tips: [
      "Download offline Chinese dictionary packs for use without internet",
      "Use the handwriting input to draw characters you see on signs",
      "Tap any character in a definition to look it up instantly",
      "The flashcard system is excellent for learning basic Mandarin before your trip",
      "Free version is fully functional; premium adds audio pronunciation and extra dictionaries",
    ],
    setupSteps: [
      { title: "Download Pleco", detail: "iOS and Android. The free version is excellent. No registration required." },
      { title: "Download the offline dictionary", detail: "Settings → Manage Dictionaries → Download offline packs. Use without internet anywhere in China." },
      { title: "Use the flashcard system", detail: "Before your trip, add basic survival Chinese words (numbers, food words, transport words) and review them daily." },
      { title: "Set up handwriting input", detail: "In the search bar, tap the 'Draw' button → draw characters with your finger. Perfect for signs and menus." },
      { title: "Use the document reader", detail: "Paste Chinese text into Pleco's reader to tap any word for an instant definition. Great for decoding menus." },
      { title: "Learn the 100 most common characters", detail: "Pleco's built-in flashcard sets include HSK vocab. Even knowing 50–100 characters transforms your China experience." },
    ],
    color: "text-indigo-400",
    emoji: "📖",
  },
];

export function getAppBySlug(slug: string): App | undefined {
  return APPS.find((a) => a.slug === slug);
}
